openapi: 3.0.0

info:
  title: Customer Management API
  description: |-
    Test API for Customer Management.
  version: 0.0.1

servers:
  - url: http://localhost:8080/v1
    description: A localy developed API, e.g. Development (local) server

tags:
  - name: Customers
    description: Managing customers
  - name: Contacts
    description: Managing contacts
  - name: Addresses
    description: Managing addresses

paths:
  /customers:
    get:
      tags:
        - Customers
      summary: Returns a list of customers.
      responses:
        '200':
          description: OK
          content:
            application/json:
              # TODO: Add pagination later
              schema:
                type: array
                items:  
                  $ref: "#/components/schemas/Customer"
    post:
      tags:
       - Customers
      summary: Creates a new customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerPost"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
            
  /customers/{id}:
    get:
      tags:
        - Customers
      summary: Returns a customers for a given ID.
      parameters:
        - name: id
          in: path
          description: ID of the customer to return
          required: true
          schema:
            format: integer
        
      responses:
        '200':
          description: OK
          content:
            application/json:
              # TODO: Add pagination later
              schema:
                type: array
                items:  
                  $ref: "#/components/schemas/Customer"
  
  /import/customers:
    post:
      tags:
        - Imports
      summary: Endpoint for importing customers from CSV/XLSX files.
      requestBody:
        description: Upload the file with customers for import
        content:
           application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Validation error
  
  /import/contacts:
    post:
      tags:
          - Imports
      summary: Endpoint for importing contacts from CSV/XLSX files.
      requestBody:
        description: Upload the file with customers for import
        content:
           application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: string
              format: binary      
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Validation error

  /export/customers:
    get:
      tags:
        - Exports
      summary: Endpoint for exporting customers from database to CSV/XLSX files.
      responses:
        '200':
          description: Success
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
  
  /export/contacts:
    get:
      tags:
        - Exports
      summary: Endpoint for exporting contacts from database to CSV/XLSX files.
      responses:
        '200':
          description: Success
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
  
  /export/addresses:
    get:
      tags:
        - Exports
      summary: Endpoint for exporting addresses from database to CSV/XLSX files.
      responses:
        '200':
          description: Success
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
  
components:
  schemas:
    Response:
      type: object
      properties:
        status:
          type: string
          format: string
          example: OK
    
    Customer:
      type: object
      properties:
        id:
          type: integer
          example: 32
        name:
          type: string
          example: Test Inc.
        short_name:
          type: string
          example: tt01
        vat_number:
          type: string
          example: 265 478
        vat_apply:
          type: boolean
          example: true
        registration_number:
          type: string
          example: 24378253
        duns_number:
          type: string
          example: 23678167
        tax_exempt:
          type: boolean
          example: false
        language:
          type: string
          example: en
        email:
          type: string
          example: test@test.com
        phone:
          type: string
          example: 38162558587
        fax:
          type: string
          example: 23467237868

    CustomerPost:
      type: object
      properties:
        name:
          type: string
          example: Test Inc.
        short_name:
          type: string
          example: tt01
        vat_number:
          type: string
          example: 265 478
        vat_apply:
          type: boolean
          example: true
        registration_number:
          type: string
          example: 24378253
        duns_number:
          type: string
          example: 23678167
        tax_exempt:
          type: boolean
          example: false
        language:
          type: string
          example: en
        email:
          type: string
          example: test@test.com
        phone:
          type: string
          example: 38162558587
        fax:
          type: string
          example: 23467237868
