version: '3'

services:

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crm-db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - backend

  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile # relative to context
    container_name: crm-go-api
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ../.env
    networks:
      - backend
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - redis-data:/data
    networks:
        - backend

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - redisinsight-data:/db
    networks:
      - backend

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8512:8080
    volumes:
      - ../doc/openapi/:/swagger/
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml  # relative to container's directory (i.e. /swagger/)
      BASE_URL: /swagger  # access at http://localhost:8512/swagger/
    networks:
      - backend

volumes:
  mysql-db:
  redis-data:
  redisinsight-data:

networks:
  backend:
